/**
 * @fileoverview gRPC-Web generated client stub for zbay
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.4.2
// 	protoc              v3.14.0
// source: attendant.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');


var google_protobuf_empty_pb = require('google-protobuf/google/protobuf/empty_pb.js')

var google_protobuf_timestamp_pb = require('google-protobuf/google/protobuf/timestamp_pb.js')
const proto = {};
proto.zbay = require('./attendant_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.zbay.AttendantsClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'binary';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.zbay.AttendantsPromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'binary';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.zbay.Attendant,
 *   !proto.zbay.Attendant>}
 */
const methodDescriptor_Attendants_Add = new grpc.web.MethodDescriptor(
  '/zbay.Attendants/Add',
  grpc.web.MethodType.UNARY,
  proto.zbay.Attendant,
  proto.zbay.Attendant,
  /**
   * @param {!proto.zbay.Attendant} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.zbay.Attendant.deserializeBinary
);


/**
 * @param {!proto.zbay.Attendant} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.zbay.Attendant)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.zbay.Attendant>|undefined}
 *     The XHR Node Readable Stream
 */
proto.zbay.AttendantsClient.prototype.add =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/zbay.Attendants/Add',
      request,
      metadata || {},
      methodDescriptor_Attendants_Add,
      callback);
};


/**
 * @param {!proto.zbay.Attendant} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.zbay.Attendant>}
 *     Promise that resolves to the response
 */
proto.zbay.AttendantsPromiseClient.prototype.add =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/zbay.Attendants/Add',
      request,
      metadata || {},
      methodDescriptor_Attendants_Add);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.zbay.Attendant,
 *   !proto.zbay.Attendant>}
 */
const methodDescriptor_Attendants_Get = new grpc.web.MethodDescriptor(
  '/zbay.Attendants/Get',
  grpc.web.MethodType.UNARY,
  proto.zbay.Attendant,
  proto.zbay.Attendant,
  /**
   * @param {!proto.zbay.Attendant} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.zbay.Attendant.deserializeBinary
);


/**
 * @param {!proto.zbay.Attendant} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.zbay.Attendant)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.zbay.Attendant>|undefined}
 *     The XHR Node Readable Stream
 */
proto.zbay.AttendantsClient.prototype.get =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/zbay.Attendants/Get',
      request,
      metadata || {},
      methodDescriptor_Attendants_Get,
      callback);
};


/**
 * @param {!proto.zbay.Attendant} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.zbay.Attendant>}
 *     Promise that resolves to the response
 */
proto.zbay.AttendantsPromiseClient.prototype.get =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/zbay.Attendants/Get',
      request,
      metadata || {},
      methodDescriptor_Attendants_Get);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.zbay.Attendant,
 *   !proto.zbay.Attendant>}
 */
const methodDescriptor_Attendants_Update = new grpc.web.MethodDescriptor(
  '/zbay.Attendants/Update',
  grpc.web.MethodType.UNARY,
  proto.zbay.Attendant,
  proto.zbay.Attendant,
  /**
   * @param {!proto.zbay.Attendant} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.zbay.Attendant.deserializeBinary
);


/**
 * @param {!proto.zbay.Attendant} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.zbay.Attendant)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.zbay.Attendant>|undefined}
 *     The XHR Node Readable Stream
 */
proto.zbay.AttendantsClient.prototype.update =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/zbay.Attendants/Update',
      request,
      metadata || {},
      methodDescriptor_Attendants_Update,
      callback);
};


/**
 * @param {!proto.zbay.Attendant} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.zbay.Attendant>}
 *     Promise that resolves to the response
 */
proto.zbay.AttendantsPromiseClient.prototype.update =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/zbay.Attendants/Update',
      request,
      metadata || {},
      methodDescriptor_Attendants_Update);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.zbay.Attendant,
 *   !proto.zbay.Attendant>}
 */
const methodDescriptor_Attendants_List = new grpc.web.MethodDescriptor(
  '/zbay.Attendants/List',
  grpc.web.MethodType.SERVER_STREAMING,
  proto.zbay.Attendant,
  proto.zbay.Attendant,
  /**
   * @param {!proto.zbay.Attendant} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.zbay.Attendant.deserializeBinary
);


/**
 * @param {!proto.zbay.Attendant} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.zbay.Attendant>}
 *     The XHR Node Readable Stream
 */
proto.zbay.AttendantsClient.prototype.list =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/zbay.Attendants/List',
      request,
      metadata || {},
      methodDescriptor_Attendants_List);
};


/**
 * @param {!proto.zbay.Attendant} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.zbay.Attendant>}
 *     The XHR Node Readable Stream
 */
proto.zbay.AttendantsPromiseClient.prototype.list =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/zbay.Attendants/List',
      request,
      metadata || {},
      methodDescriptor_Attendants_List);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.zbay.Attendant,
 *   !proto.google.protobuf.Empty>}
 */
const methodDescriptor_Attendants_Delete = new grpc.web.MethodDescriptor(
  '/zbay.Attendants/Delete',
  grpc.web.MethodType.UNARY,
  proto.zbay.Attendant,
  google_protobuf_empty_pb.Empty,
  /**
   * @param {!proto.zbay.Attendant} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  google_protobuf_empty_pb.Empty.deserializeBinary
);


/**
 * @param {!proto.zbay.Attendant} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.google.protobuf.Empty)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.google.protobuf.Empty>|undefined}
 *     The XHR Node Readable Stream
 */
proto.zbay.AttendantsClient.prototype.delete =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/zbay.Attendants/Delete',
      request,
      metadata || {},
      methodDescriptor_Attendants_Delete,
      callback);
};


/**
 * @param {!proto.zbay.Attendant} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.google.protobuf.Empty>}
 *     Promise that resolves to the response
 */
proto.zbay.AttendantsPromiseClient.prototype.delete =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/zbay.Attendants/Delete',
      request,
      metadata || {},
      methodDescriptor_Attendants_Delete);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.zbay.Attendant,
 *   !proto.zbay.Attendant>}
 */
const methodDescriptor_Attendants_Login = new grpc.web.MethodDescriptor(
  '/zbay.Attendants/Login',
  grpc.web.MethodType.UNARY,
  proto.zbay.Attendant,
  proto.zbay.Attendant,
  /**
   * @param {!proto.zbay.Attendant} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.zbay.Attendant.deserializeBinary
);


/**
 * @param {!proto.zbay.Attendant} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.zbay.Attendant)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.zbay.Attendant>|undefined}
 *     The XHR Node Readable Stream
 */
proto.zbay.AttendantsClient.prototype.login =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/zbay.Attendants/Login',
      request,
      metadata || {},
      methodDescriptor_Attendants_Login,
      callback);
};


/**
 * @param {!proto.zbay.Attendant} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.zbay.Attendant>}
 *     Promise that resolves to the response
 */
proto.zbay.AttendantsPromiseClient.prototype.login =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/zbay.Attendants/Login',
      request,
      metadata || {},
      methodDescriptor_Attendants_Login);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.zbay.Attendant,
 *   !proto.zbay.Attendant>}
 */
const methodDescriptor_Attendants_Certificate = new grpc.web.MethodDescriptor(
  '/zbay.Attendants/Certificate',
  grpc.web.MethodType.UNARY,
  proto.zbay.Attendant,
  proto.zbay.Attendant,
  /**
   * @param {!proto.zbay.Attendant} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.zbay.Attendant.deserializeBinary
);


/**
 * @param {!proto.zbay.Attendant} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.zbay.Attendant)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.zbay.Attendant>|undefined}
 *     The XHR Node Readable Stream
 */
proto.zbay.AttendantsClient.prototype.certificate =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/zbay.Attendants/Certificate',
      request,
      metadata || {},
      methodDescriptor_Attendants_Certificate,
      callback);
};


/**
 * @param {!proto.zbay.Attendant} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.zbay.Attendant>}
 *     Promise that resolves to the response
 */
proto.zbay.AttendantsPromiseClient.prototype.certificate =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/zbay.Attendants/Certificate',
      request,
      metadata || {},
      methodDescriptor_Attendants_Certificate);
};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.zbay.AddressesClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'binary';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.zbay.AddressesPromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'binary';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.zbay.Address,
 *   !proto.zbay.Address>}
 */
const methodDescriptor_Addresses_Add = new grpc.web.MethodDescriptor(
  '/zbay.Addresses/Add',
  grpc.web.MethodType.UNARY,
  proto.zbay.Address,
  proto.zbay.Address,
  /**
   * @param {!proto.zbay.Address} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.zbay.Address.deserializeBinary
);


/**
 * @param {!proto.zbay.Address} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.zbay.Address)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.zbay.Address>|undefined}
 *     The XHR Node Readable Stream
 */
proto.zbay.AddressesClient.prototype.add =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/zbay.Addresses/Add',
      request,
      metadata || {},
      methodDescriptor_Addresses_Add,
      callback);
};


/**
 * @param {!proto.zbay.Address} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.zbay.Address>}
 *     Promise that resolves to the response
 */
proto.zbay.AddressesPromiseClient.prototype.add =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/zbay.Addresses/Add',
      request,
      metadata || {},
      methodDescriptor_Addresses_Add);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.zbay.Address,
 *   !proto.zbay.Address>}
 */
const methodDescriptor_Addresses_Get = new grpc.web.MethodDescriptor(
  '/zbay.Addresses/Get',
  grpc.web.MethodType.UNARY,
  proto.zbay.Address,
  proto.zbay.Address,
  /**
   * @param {!proto.zbay.Address} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.zbay.Address.deserializeBinary
);


/**
 * @param {!proto.zbay.Address} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.zbay.Address)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.zbay.Address>|undefined}
 *     The XHR Node Readable Stream
 */
proto.zbay.AddressesClient.prototype.get =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/zbay.Addresses/Get',
      request,
      metadata || {},
      methodDescriptor_Addresses_Get,
      callback);
};


/**
 * @param {!proto.zbay.Address} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.zbay.Address>}
 *     Promise that resolves to the response
 */
proto.zbay.AddressesPromiseClient.prototype.get =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/zbay.Addresses/Get',
      request,
      metadata || {},
      methodDescriptor_Addresses_Get);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.zbay.Address,
 *   !proto.zbay.Address>}
 */
const methodDescriptor_Addresses_Update = new grpc.web.MethodDescriptor(
  '/zbay.Addresses/Update',
  grpc.web.MethodType.UNARY,
  proto.zbay.Address,
  proto.zbay.Address,
  /**
   * @param {!proto.zbay.Address} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.zbay.Address.deserializeBinary
);


/**
 * @param {!proto.zbay.Address} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.zbay.Address)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.zbay.Address>|undefined}
 *     The XHR Node Readable Stream
 */
proto.zbay.AddressesClient.prototype.update =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/zbay.Addresses/Update',
      request,
      metadata || {},
      methodDescriptor_Addresses_Update,
      callback);
};


/**
 * @param {!proto.zbay.Address} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.zbay.Address>}
 *     Promise that resolves to the response
 */
proto.zbay.AddressesPromiseClient.prototype.update =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/zbay.Addresses/Update',
      request,
      metadata || {},
      methodDescriptor_Addresses_Update);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.zbay.Address,
 *   !proto.google.protobuf.Empty>}
 */
const methodDescriptor_Addresses_Delete = new grpc.web.MethodDescriptor(
  '/zbay.Addresses/Delete',
  grpc.web.MethodType.UNARY,
  proto.zbay.Address,
  google_protobuf_empty_pb.Empty,
  /**
   * @param {!proto.zbay.Address} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  google_protobuf_empty_pb.Empty.deserializeBinary
);


/**
 * @param {!proto.zbay.Address} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.google.protobuf.Empty)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.google.protobuf.Empty>|undefined}
 *     The XHR Node Readable Stream
 */
proto.zbay.AddressesClient.prototype.delete =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/zbay.Addresses/Delete',
      request,
      metadata || {},
      methodDescriptor_Addresses_Delete,
      callback);
};


/**
 * @param {!proto.zbay.Address} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.google.protobuf.Empty>}
 *     Promise that resolves to the response
 */
proto.zbay.AddressesPromiseClient.prototype.delete =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/zbay.Addresses/Delete',
      request,
      metadata || {},
      methodDescriptor_Addresses_Delete);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.zbay.Attendant,
 *   !proto.zbay.Address>}
 */
const methodDescriptor_Addresses_List = new grpc.web.MethodDescriptor(
  '/zbay.Addresses/List',
  grpc.web.MethodType.SERVER_STREAMING,
  proto.zbay.Attendant,
  proto.zbay.Address,
  /**
   * @param {!proto.zbay.Attendant} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.zbay.Address.deserializeBinary
);


/**
 * @param {!proto.zbay.Attendant} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.zbay.Address>}
 *     The XHR Node Readable Stream
 */
proto.zbay.AddressesClient.prototype.list =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/zbay.Addresses/List',
      request,
      metadata || {},
      methodDescriptor_Addresses_List);
};


/**
 * @param {!proto.zbay.Attendant} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.zbay.Address>}
 *     The XHR Node Readable Stream
 */
proto.zbay.AddressesPromiseClient.prototype.list =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/zbay.Addresses/List',
      request,
      metadata || {},
      methodDescriptor_Addresses_List);
};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.zbay.MemosClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'binary';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.zbay.MemosPromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'binary';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.zbay.Memo,
 *   !proto.zbay.Memo>}
 */
const methodDescriptor_Memos_Add = new grpc.web.MethodDescriptor(
  '/zbay.Memos/Add',
  grpc.web.MethodType.UNARY,
  proto.zbay.Memo,
  proto.zbay.Memo,
  /**
   * @param {!proto.zbay.Memo} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.zbay.Memo.deserializeBinary
);


/**
 * @param {!proto.zbay.Memo} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.zbay.Memo)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.zbay.Memo>|undefined}
 *     The XHR Node Readable Stream
 */
proto.zbay.MemosClient.prototype.add =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/zbay.Memos/Add',
      request,
      metadata || {},
      methodDescriptor_Memos_Add,
      callback);
};


/**
 * @param {!proto.zbay.Memo} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.zbay.Memo>}
 *     Promise that resolves to the response
 */
proto.zbay.MemosPromiseClient.prototype.add =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/zbay.Memos/Add',
      request,
      metadata || {},
      methodDescriptor_Memos_Add);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.zbay.Memo,
 *   !proto.zbay.Memo>}
 */
const methodDescriptor_Memos_Get = new grpc.web.MethodDescriptor(
  '/zbay.Memos/Get',
  grpc.web.MethodType.UNARY,
  proto.zbay.Memo,
  proto.zbay.Memo,
  /**
   * @param {!proto.zbay.Memo} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.zbay.Memo.deserializeBinary
);


/**
 * @param {!proto.zbay.Memo} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.zbay.Memo)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.zbay.Memo>|undefined}
 *     The XHR Node Readable Stream
 */
proto.zbay.MemosClient.prototype.get =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/zbay.Memos/Get',
      request,
      metadata || {},
      methodDescriptor_Memos_Get,
      callback);
};


/**
 * @param {!proto.zbay.Memo} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.zbay.Memo>}
 *     Promise that resolves to the response
 */
proto.zbay.MemosPromiseClient.prototype.get =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/zbay.Memos/Get',
      request,
      metadata || {},
      methodDescriptor_Memos_Get);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.zbay.Memo,
 *   !proto.zbay.Memo>}
 */
const methodDescriptor_Memos_Update = new grpc.web.MethodDescriptor(
  '/zbay.Memos/Update',
  grpc.web.MethodType.UNARY,
  proto.zbay.Memo,
  proto.zbay.Memo,
  /**
   * @param {!proto.zbay.Memo} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.zbay.Memo.deserializeBinary
);


/**
 * @param {!proto.zbay.Memo} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.zbay.Memo)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.zbay.Memo>|undefined}
 *     The XHR Node Readable Stream
 */
proto.zbay.MemosClient.prototype.update =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/zbay.Memos/Update',
      request,
      metadata || {},
      methodDescriptor_Memos_Update,
      callback);
};


/**
 * @param {!proto.zbay.Memo} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.zbay.Memo>}
 *     Promise that resolves to the response
 */
proto.zbay.MemosPromiseClient.prototype.update =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/zbay.Memos/Update',
      request,
      metadata || {},
      methodDescriptor_Memos_Update);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.zbay.Memo,
 *   !proto.google.protobuf.Empty>}
 */
const methodDescriptor_Memos_Delete = new grpc.web.MethodDescriptor(
  '/zbay.Memos/Delete',
  grpc.web.MethodType.UNARY,
  proto.zbay.Memo,
  google_protobuf_empty_pb.Empty,
  /**
   * @param {!proto.zbay.Memo} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  google_protobuf_empty_pb.Empty.deserializeBinary
);


/**
 * @param {!proto.zbay.Memo} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.google.protobuf.Empty)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.google.protobuf.Empty>|undefined}
 *     The XHR Node Readable Stream
 */
proto.zbay.MemosClient.prototype.delete =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/zbay.Memos/Delete',
      request,
      metadata || {},
      methodDescriptor_Memos_Delete,
      callback);
};


/**
 * @param {!proto.zbay.Memo} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.google.protobuf.Empty>}
 *     Promise that resolves to the response
 */
proto.zbay.MemosPromiseClient.prototype.delete =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/zbay.Memos/Delete',
      request,
      metadata || {},
      methodDescriptor_Memos_Delete);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.zbay.Attendant,
 *   !proto.zbay.Memo>}
 */
const methodDescriptor_Memos_List = new grpc.web.MethodDescriptor(
  '/zbay.Memos/List',
  grpc.web.MethodType.SERVER_STREAMING,
  proto.zbay.Attendant,
  proto.zbay.Memo,
  /**
   * @param {!proto.zbay.Attendant} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.zbay.Memo.deserializeBinary
);


/**
 * @param {!proto.zbay.Attendant} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.zbay.Memo>}
 *     The XHR Node Readable Stream
 */
proto.zbay.MemosClient.prototype.list =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/zbay.Memos/List',
      request,
      metadata || {},
      methodDescriptor_Memos_List);
};


/**
 * @param {!proto.zbay.Attendant} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.zbay.Memo>}
 *     The XHR Node Readable Stream
 */
proto.zbay.MemosPromiseClient.prototype.list =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/zbay.Memos/List',
      request,
      metadata || {},
      methodDescriptor_Memos_List);
};


module.exports = proto.zbay;

